### PR TITLE
Updates and changes to match ultra96-v2 board

### PR DESCRIPTION
**Pull request by narrucmot**
Did the commit and push from the master branch this time.  Hopefully this works.  Let me know.

### CODE REVIEW

**Comment by mharth** [comment]
can you  open the pull request against ultra96v2 branch

**Comment by narrucmot** [comment]
I opened this pull request in my web browser.  Was there something you wanted me to do here?

--Tom

**Comment by mharth** [comment]
open the pull request to this branch : https://github.com/Xilinx/ultra96-startup-pages/tree/ultra96v2 not master

**Comment by narrucmot** [comment]
OK, I have it opened now

--Tom

**Pull request closed without merging**
