### PR TITLE
Updates and changes to match Ultra96-V2 board

### PR DESCRIPTION
**Pull request by narrucmot**
I created a new "Ultra96-V2" branch and put my file changes and additions in there.  Please let me know if there is anything else I need to do.

Thanks!
--Tom

### CODE REVIEW

**Review by mharth — CHANGES_REQUESTED** [review]
You have added these lines, we should not add these in license file. Please update the pull request

 Use of the Software is limited solely to applications:
- (a) running on a Xilinx device, or
- (b) that interact with a Xilinx device through a bus or interconnect.

**Review by narrucmot — COMMENTED** [review]
I don't know how those lines were added to the file headers.  I have removed the lines.  Ready for further review.  Thanks!

**Comment by mharth** [comment]
can you merge the changes to a single patch instead of editing the license file in individual patches

**Comment by narrucmot** [comment]
OK, I edited the files in my local repo instead of via github web.  Did a fresh commit and push.  Is this better?

**Comment by mharth** [comment]
can you squash and force push to your tree, it should be a single commit patch in your tree on top of master. It now looks like it does have multiple commits along with a merge

**Comment by narrucmot** [comment]
Sorry Manju, this task and process of doing a git pull request is still new to me.  I think I see what you mean about the "multiple commits along with a merge".  I will see what I can do to clean this up and send it back to you.

**Comment by narrucmot** [comment]
OK, you should see a squashed commit now?

**Comment by mharth** [comment]
Can you get rid of  "Merge branch 'Ultra96-V2' of https://github.com/narrucmot/ultra96-sta…  …
e41b01e"

Its easier if you have a rebase tree on master with a single patch.

**Comment by narrucmot** [comment]
I don't know how to do that.


Sent with BlackBerry Work (www.blackberry.com)
________________________________

**Pull request closed without merging**
